import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

class HTMLReporter:
    def __init__(self, output_dir: str):
        self.output_dir = output_dir

    def generate_report(self, analysis_results: dict, language: str = 'en'):
        """
        Generate an HTML report.
        language: 'en' or 'he'
        """
        is_hebrew = language == 'he'
        filename = "Israeli_Long_Opportunity_Report_HE.html" if is_hebrew else "Israeli_Long_Opportunity_Report.html"
        output_path = os.path.join(self.output_dir, filename)
        
        logger.info(f"📄 Generating HTML report ({language}): {output_path}")
        
        # CSS & Style
        direction = "rtl" if is_hebrew else "ltr"
        font_family = "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"
        text_align = "right" if is_hebrew else "left"
        
        html_content = f"""
        <!DOCTYPE html>
        <html lang="{language}" dir="{direction}">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Systemic Risk Report - {language.upper()}</title>
            <style>
                body {{
                    font-family: {font_family};
                    background-color: #f4f4f9;
                    color: #333;
                    line-height: 1.6;
                    margin: 0;
                    padding: 20px;
                }}
                .container {{
                    max-width: 900px;
                    margin: 0 auto;
                    background: white;
                    padding: 40px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                    border-radius: 8px;
                }}
                h1, h2, h3 {{
                    color: #2c3e50;
                }}
                h1 {{
                    border-bottom: 2px solid #3498db;
                    padding-bottom: 10px;
                }}
                .header-info {{
                    color: #7f8c8d;
                    font-size: 0.9em;
                    margin-bottom: 30px;
                }}
                .section {{
                    margin-bottom: 40px;
                    padding: 20px;
                    background: #fff;
                    border: 1px solid #eee;
                    border-radius: 5px;
                }}
                .high-risk {{
                    border-left: 5px solid #e74c3c;
                }}
                .medium-risk {{
                    border-left: 5px solid #f39c12;
                }}
                .low-risk {{
                    border-left: 5px solid #27ae60;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 20px 0;
                }}
                th, td {{
                    padding: 12px;
                    border-bottom: 1px solid #ddd;
                    text-align: {text_align};
                }}
                th {{
                    background-color: #f8f9fa;
                    font-weight: bold;
                }}
                .score-badge {{
                    display: inline-block;
                    padding: 4px 8px;
                    border-radius: 4px;
                    color: white;
                    font-weight: bold;
                }}
                .score-high {{ background-color: #e74c3c; }}
                .score-med {{ background-color: #f39c12; }}
                .score-low {{ background-color: #27ae60; }}
                
                .company-card {{
                    background: #fdfdfd;
                    border: 1px solid #e1e1e1;
                    padding: 20px;
                    margin-bottom: 20px;
                    border-radius: 6px;
                }}
                .source-link {{
                    font-size: 0.85em;
                    color: #3498db;
                    text-decoration: none;
                }}
                .disclaimer {{
                    margin-top: 50px;
                    padding: 20px;
                    background: #fff3cd;
                    border: 1px solid #ffeeba;
                    color: #856404;
                    font-size: 0.9em;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <h1>{'דוח הזדמנויות לונג - מניות וקרנות סל כשרות' if is_hebrew else 'Long Opportunity Report - Israeli Stocks + Kosher ETFs'}</h1>
                <div class="header-info">
                    {'תאריך' if is_hebrew else 'Date'}: {datetime.now().strftime('%Y-%m-%d %H:%M')}<br>
                    {'נוצר ע"י' if is_hebrew else 'Generated by'}: AI Autonomous Agent
                </div>

                <!-- Government Data Section -->
                <div class="section">
                    <h2>{'📊 נתוני ממשלה (מאקרו)' if is_hebrew else '📊 Government Data (Macro)'}</h2>
                    <ul>
                        <li><strong>{'התחלות בנייה' if is_hebrew else 'Construction Starts'}:</strong> 
                            {analysis_results.get('gov_data_summary', {}).get('construction_starts', {}).get('trend', 'N/A')}
                        </li>
                        <li><strong>{'דירות חדשות שנמכרו' if is_hebrew else 'New Dwellings Sold'}:</strong> 
                            {analysis_results.get('gov_data_summary', {}).get('new_dwellings_sold', {}).get('trend', 'N/A')}
                        </li>
                        <li><strong>{'מדד תשומות הבנייה' if is_hebrew else 'Construction Input Price Index'}:</strong> 
                            {analysis_results.get('gov_data_summary', {}).get('cpi_construction', {}).get('trend', 'N/A')}
                        </li>
                    </ul>
                    <p style="font-size: 0.9em; color: #666;">
                        {'מקור: data.gov.il' if is_hebrew else 'Source: data.gov.il'}
                    </p>
                </div>

                <div class="section">
                    <h2>{'✅ מועמדים מובילים ללונג' if is_hebrew else '✅ Top Long Candidates'}</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>{'סימול' if is_hebrew else 'Symbol'}</th>
                                <th>{'קטגוריה' if is_hebrew else 'Bucket'}</th>
                                <th>{'ציון' if is_hebrew else 'Score'}</th>
                                <th>{'המלצה' if is_hebrew else 'Recommendation'}</th>
                            </tr>
                        </thead>
                        <tbody>
        """
        
        top_candidates = analysis_results.get("top_long_candidates", [])
        if not top_candidates:
            html_content += f"<tr><td colspan='4'>{'לא נמצאו מועמדים' if is_hebrew else 'No candidates found'}</td></tr>"
        else:
            for c in top_candidates[:5]:
                score_class = "score-high" if c['long_score'] > 75 else "score-med" if c['long_score'] > 60 else "score-low"
                
                # Translate fields if Hebrew
                sector = c.get('bucket', '')
                rec = c['recommendation']
                if is_hebrew:
                    # Simple mapping or use the translated field if available
                    rec = c.get('recommendation_he', rec)
                
                html_content += f"""
                            <tr>
                                <td><strong>{c['symbol']}</strong></td>
                                <td>{sector}</td>
                                <td><span class="score-badge {score_class}">{c['long_score']:.1f}</span></td>
                                <td>{rec}</td>
                            </tr>
                """

        html_content += """
                        </tbody>
                    </table>
                </div>
        """
        
        # Portfolio
        portfolio = analysis_results.get('portfolio', {}) or {}
        positions = portfolio.get('positions', []) or []

        html_content += f"""
                <div class="section">
                    <h2>{'💼 תיק מודל ($100k)' if is_hebrew else '💼 Model Portfolio ($100k)'} </h2>
                    <p style="font-size: 0.9em; color: #666;">
                        {'מזומן' if is_hebrew else 'Cash'}: {portfolio.get('cash_reserve', 'N/A')} ({portfolio.get('cash_reserve_pct', 'N/A')})
                    </p>
                    <table>
                        <thead>
                            <tr>
                                <th>{'סימול' if is_hebrew else 'Symbol'}</th>
                                <th>{'שם' if is_hebrew else 'Name'}</th>
                                <th>{'סוג' if is_hebrew else 'Type'}</th>
                                <th>{'משקל יעד' if is_hebrew else 'Target Wt'}</th>
                                <th>{'ערך יעד' if is_hebrew else 'Target Value'}</th>
                                <th>{'מניות' if is_hebrew else 'Shares'}</th>
                            </tr>
                        </thead>
                        <tbody>
        """

        if not positions:
            html_content += f"<tr><td colspan='6'>{'אין הקצאות' if is_hebrew else 'No allocations (missing candidates/prices)'}</td></tr>"
        else:
            for p in positions:
                html_content += f"""
                            <tr>
                                <td><strong>{p.get('symbol','')}</strong></td>
                                <td>{p.get('name','')}</td>
                                <td>{p.get('asset_type','')}</td>
                                <td>{p.get('target_weight','')}</td>
                                <td>{p.get('target_value','')}</td>
                                <td>{p.get('shares','')}</td>
                            </tr>
                """

        html_content += """
                        </tbody>
                    </table>
                </div>
        """

        # Detailed Analysis
        html_content += f"<h2>{'🔍 ניתוח מעמיק' if is_hebrew else '🔍 Deep Dive Analysis'}</h2>"
        
        for sector, companies in analysis_results.get("bucket_analysis", {}).items():
            html_content += f"<h3>{sector.upper()}</h3>"
            
            for co in companies:
                score_class = "high-risk" if co['long_score'] > 75 else "medium-risk" if co['long_score'] > 60 else "low-risk"
                
                # Get text based on language
                if is_hebrew:
                    fin_reason = co['details'].get('fundamental_reasoning_he', 'N/A')
                    macro_reason = co['details'].get('macro_reasoning_he', 'N/A')
                    contagion = ''
                else:
                    fin_reason = co['details'].get('fundamental_reasoning_en', 'N/A')
                    macro_reason = co['details'].get('macro_reasoning_en', 'N/A')
                    contagion = ''

                html_content += f"""
                <div class="company-card {score_class}">
                    <h4>{co['symbol']} <span style="font-size:0.8em; color:#666;">(Score: {co['long_score']:.1f})</span></h4>
                    <a href="https://finance.yahoo.com/quote/{co['symbol']}" class="source-link" target="_blank">
                        {'מקור נתונים: Yahoo Finance' if is_hebrew else 'Source: Yahoo Finance'}
                    </a>
                    
                    <p><strong>{'ניתוח יסודות' if is_hebrew else 'Fundamental Analysis'}:</strong><br>
                    {fin_reason}</p>
                    
                    <p><strong>{'ניתוח מאקרו' if is_hebrew else 'Macro Analysis'}:</strong><br>
                    {macro_reason}</p>
                """
                
                if contagion:
                    html_content += f"""
                    <p style="color: #d35400; background: #fae5d3; padding: 10px; border-radius: 4px;">
                        <strong>{'⚠️ הערת הדבקה' if is_hebrew else '⚠️ Contagion Note'}:</strong> {contagion}
                    </p>
                    """
                
                html_content += "</div>"

        # Disclaimer
        html_content += f"""
                <div class="disclaimer">
                    <strong>{'הבהרה משפטית' if is_hebrew else 'DISCLAIMER'}:</strong><br>
                    {'דוח זה נוצר על ידי בינה מלאכותית למטרות אינפורמטיביות בלבד. אין לראות בו ייעוץ פיננסי.' if is_hebrew else 'This report is generated by AI for informational purposes only. It does not constitute financial advice.'}
                </div>
            </div>
        </body>
        </html>
        """
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        logger.info(f"✅ HTML Report generated: {output_path}")
